# Generated by Django 3.0.7 on 2020-07-08 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(default=datetime.date(2020, 7, 8)),
        ),
    ]
